//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 6 files.
  struct file {
    /// Resource file `blueSky.json`.
    static let blueSkyJson = Rswift.FileResource(bundle: R.hostingBundle, name: "blueSky", pathExtension: "json")
    /// Resource file `icon.json`.
    static let iconJson = Rswift.FileResource(bundle: R.hostingBundle, name: "icon", pathExtension: "json")
    /// Resource file `icon2.json`.
    static let icon2Json = Rswift.FileResource(bundle: R.hostingBundle, name: "icon2", pathExtension: "json")
    /// Resource file `rainy-weather.json`.
    static let rainyWeatherJson = Rswift.FileResource(bundle: R.hostingBundle, name: "rainy-weather", pathExtension: "json")
    /// Resource file `thunder.json`.
    static let thunderJson = Rswift.FileResource(bundle: R.hostingBundle, name: "thunder", pathExtension: "json")
    /// Resource file `windy-weather.json`.
    static let windyWeatherJson = Rswift.FileResource(bundle: R.hostingBundle, name: "windy-weather", pathExtension: "json")

    /// `bundle.url(forResource: "blueSky", withExtension: "json")`
    static func blueSkyJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.blueSkyJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "icon", withExtension: "json")`
    static func iconJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.iconJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "icon2", withExtension: "json")`
    static func icon2Json(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.icon2Json
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "rainy-weather", withExtension: "json")`
    static func rainyWeatherJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.rainyWeatherJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "thunder", withExtension: "json")`
    static func thunderJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.thunderJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "windy-weather", withExtension: "json")`
    static func windyWeatherJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.windyWeatherJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `clouds`.
    static let clouds = Rswift.ImageResource(bundle: R.hostingBundle, name: "clouds")
    /// Image `dark`.
    static let dark = Rswift.ImageResource(bundle: R.hostingBundle, name: "dark")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "clouds", bundle: ..., traitCollection: ...)`
    static func clouds(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clouds, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "dark", bundle: ..., traitCollection: ...)`
    static func dark(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dark, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    /// Nib `HomeVC`.
    static let homeVC = _R.nib._HomeVC()
    /// Nib `OnboardingVC`.
    static let onboardingVC = _R.nib._OnboardingVC()
    /// Nib `SplashVC`.
    static let splashVC = _R.nib._SplashVC()
    /// Nib `XButton`.
    static let xButton = _R.nib._XButton()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "HomeVC", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.homeVC) instead")
    static func homeVC(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.homeVC)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "OnboardingVC", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.onboardingVC) instead")
    static func onboardingVC(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.onboardingVC)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SplashVC", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.splashVC) instead")
    static func splashVC(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.splashVC)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "XButton", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.xButton) instead")
    static func xButton(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.xButton)
    }
    #endif

    static func homeVC(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.homeVC.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func onboardingVC(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.onboardingVC.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func splashVC(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.splashVC.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func xButton(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.xButton.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _HomeVC.validate()
      try _OnboardingVC.validate()
    }

    struct _HomeVC: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "HomeVC"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "clouds", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'clouds' is used in nib 'HomeVC', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _OnboardingVC: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "OnboardingVC"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "arrow.right") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'arrow.right' is used in nib 'OnboardingVC', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _SplashVC: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SplashVC"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    struct _XButton: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "XButton"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
